const menu = [
    {
        id: 1,
        title: 'boAt Newly Launched Wave Call Smart Watch with Bluetooth Calling, Dial Pad, 1.69” HD Display, Sharper Resolution, Slim Design, 150+ Watch Faces, HR &',
        category: 'Electronics',
        price: '₹2,865',
        img: 'https://m.media-amazon.com/images/I/61Nbyy-SeGL._AC_UL320_.jpg',

    },
    {
        id: 2,
        title: 'boAt Xtend Smartwatch with Alexa Built-in, 1.69” HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes,..',
        category: 'Electronics',
        price: '₹3,499',
        img: 'https://m.media-amazon.com/images/I/617ysOitciL._AC_UL320_.jpg',
    },
    {
        id: 3,
        title: 'boAt Wave Lite Smartwatch with 1.69" HD Display, Sleek Metal Body, HR & SpO2 Level Monitor, 140+ Watch Faces,',
        category: 'Electronics',
        price: '₹1,499 ',
        img: 'https://m.media-amazon.com/images/I/61KPI-ZFbvL._AC_UL320_.jpg',
    },
    {
        id: 4,
        title: 'HP 14s 11th Gen Intel Core i3- 8GB RAM/256GB SSD 14inch(35.6 cm) FHD, Micro-Edge,Anti-Glare,IPS',
        category: 'Laptops',
        price: '₹36,990 ',
        img: 'https://m.media-amazon.com/images/I/81rtAL-vmwL._AC_UL320_.jpg',
    },
    {
        id: 5,
        title: 'HP 15s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 15.6-inch(39.6 cm) FHD, Micro-Edge, Anti-Glare Display/Alexa...',
        category: 'Laptops',
        price: '₹42,990',
        img: 'https://m.media-amazon.com/images/I/81PbxeJomjL._AC_UL320_.jpg',
    },
    {
        id: 7,
        title: 'HP 14s, AMD Ryzen 5-5500U 14 inches(35cm) FHD, IPS, Micro-Edge Display Laptop (8GB RAM/512GB SSD...',
        category: 'Laptops',
        price: '₹47,839',
        img: 'https://m.media-amazon.com/images/I/9128rLQ0+DL._AC_UL320_.jpg',
    },
    {
        id: 8,
        title: 'Redmi 80 cm (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black)',
        category: 'Televisions',
        price: '₹12,999 <span class="a-offscreen">₹24,999 (48% off)</span>',
        img: 'https://m.media-amazon.com/images/I/71L-lTQnJiL._AC_UL320_.jpg',
    },
    {
        id: 9,
        title: 'LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray)',
        category: 'Televisions',
        price: '₹14,990 ₹21,990 (32% off)',
        img: 'https://m.media-amazon.com/images/I/81-hT0r6zlL._AC_UL320_.jpg',
    },
    {
        id: 10,
        title: 'OnePlus 80 cm (32 inches) Y Series HD Ready Smart Android LED TV 32 Y1S (Black)',
        category: 'Televisions',
        price: '₹14,999 ₹21,999 (32% off)',
        img: 'https://m.media-amazon.com/images/I/81iLglMLueL._AC_UL320_.jpg',
    },
    {
        id: 11,
        title: 'OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black)',
        category: 'Televisions',
        price: '₹13,499 ₹19,999 (33% off)',
        img: 'https://m.media-amazon.com/images/I/71vZypjNkPS._AC_UL320_.jpg',
    },
    {
        id: 12,
        title: 'Mi 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black)',
        category: 'Televisions',
        price: '₹13,999 ₹24,999 (44% off)',
        img: 'https://m.media-amazon.com/images/I/81tD7OZ0RXL._AC_UL320_.jpg',
    },
    {
        id: 13,
        title: 'Redmi 108 cm (43 inches) 4K Ultra HD Android Smart LED TV X43 | L43R7-7AIN (Black)',
        category: 'Televisions',
        price: '₹25,999 ₹42,999 (40% off)',
        img: 'https://m.media-amazon.com/images/I/7132bixhytL._AC_UL320_.jpg',
    },
    {
        id: 14,
        title: 'Croma 80 cm (32 Inches) HD Ready LED TV CREL7369 (Black)',
        category: 'Televisions',
        price: '₹7,490 ₹20,000 (63% off)',
        img: 'https://m.media-amazon.com/images/I/718y1yr8SNL._AC_UL320_.jpg',
    },
    {
        id: 15,
        title: 'OnePlus 126 cm (50 inches) Y Series 4K Ultra HD Smart Android LED TV 50Y1S Pro (Black)',
        category: 'Televisions',
        price: '₹32,990 ₹45,999 (28% off)',
        img: 'https://m.media-amazon.com/images/I/811S0pjxeJL._AC_UL320_.jpg',
    },
    {
        id: 16,
        title: 'Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL (Glossy Black)',
        category: 'Televisions',
        price: '₹14,989 ₹22,900 (35% off)',
        img: 'https://m.media-amazon.com/images/I/7160TtJzTWL._AC_UL320_.jpg',
    },
    {
        id: 17,
        title: 'OnePlus 108 cm (43 inches) Y Series 4K Ultra HD Smart Android LED TV 43Y1S Pro (Black)',
        category: 'Televisions',
        price: '₹28,499 ₹39,999 (29% off)',
        img: 'https://m.media-amazon.com/images/I/81qoKyMES2L._AC_UL320_.jpg',
    },
    {
        id: 18,
        title: 'Vu 126 cm (50 Inches) Premium 4K Series Smart Android LED TV 50PM (Grey) (2022 Model)',
        category: 'Televisions',
        price: '₹29,440 ₹45,000 (35% off)',
        img: 'https://m.media-amazon.com/images/I/61RGMMpLQRL._AC_UL320_.jpg',
    },
    {
        id: 19,
        title: 'VW 80 cm (32 inches) HD Ready Smart LED TV VW32S (Black) (2021 Model)',
        category: 'Televisions',
        price: '₹7,777 ₹16,999 (54% off)',
        img: 'https://m.media-amazon.com/images/I/81YJUW9+ZBL._AC_UL320_.jpg',
    },
    {
        id: 20,
        title: 'VW 80 cm (32 inches) HD Ready Smart LED TV VW32S (Black) (2021 Model)',
        category: 'Televisions',
        price: '₹7,777 ₹16,999 (54% off)',
        img: 'https://m.media-amazon.com/images/I/81YJUW9+ZBL._AC_UL320_.jpg',
    },
    {
        id: 21,
        title: 'Acer Aspire 3 Intel 11th Generation Core i3 Laptop 15.6-inch (39.6 cms) Full HD (1920x1080) Anti-Glare Display -',
        category: 'Laptops',
        price: '₹37,490 ₹52,999 (29% off)',
        img: 'https://m.media-amazon.com/images/I/81CvXocfvWL._AC_UY218_.jpg',
    },
    {
        id: 22,
        title: 'Acer Aspire 3 core i5 11th Generation Processor 39.62 cm (15.6-inch) Full HD Ultra Slim Thin and Light Laptop - (8GB/256GB)',
        category: 'Laptops',
        price: '₹49,499 ₹98,765 (50% off)',
        img: 'https://m.media-amazon.com/images/I/71lM3vN5NNL._AC_UY218_.jpg',
    },
    {
        id: 23,
        title: 'Lenovo IdeaPad Slim 3 Intel Celeron N4020 15.6" (39.62cm) HD Thin & Light Laptop (8GB/256GB)',
        category: 'Laptops',
        price: '₹27,290 ₹40,490 (33% off)',
        img: 'https://m.media-amazon.com/images/I/61Dw5Z8LzJL._AC_UY218_.jpg',
    },
    {
        id: 24,
        title: 'Atomic Habits: The life-changing million copy bestsellerAtomic Habits: The life-changing million copy bestsellerAtomic Habits: The life-changing million copy…',
        category: 'Books',
        price: '₹410.00 ₹799.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/51-nXsSRfZL._AC_SX184_.jpg',
    },
    {
        id: 25,
        title: 'Ikigai: The Japanese secret to a long and happy lifeIkigai: The Japanese secret to a long and happy lifeIkigai: The Japanese secret to a long and ha…',
        category: 'Books',
        price: '₹306.00 ₹550.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/51T8OXMiB5L._AC_SX184_.jpg',
    },
    {
        id: 26,
        title: 'The Psychology of MoneyThe Psychology of MoneyThe Psychology of Money',
        category: 'Books',
        price: '₹240.00 ₹399.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/41r6F2LRf8L._AC_SX184_.jpg',
    },
    {
        id: 27,
        title: 'LIFE AND POLITICAL REALITY: Two NovellasLIFE AND POLITICAL REALITY: Two Novellas Shahidul Zahir, V. Ramaswamy, Shahroza Nahrin Paperback',
        category: 'Books',
        price: '282.00 ₹399.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/51doLrqIz2L._AC_SX184_.jpg',
    },
    {
        id: 28,
        title: 'The Lifestyle Investor: The 10 Commandments of Cash Flow Investing for Passive Income and Financial FreedomThe Lifestyle Investor: The 10 Commandments of Cash Flow Investing for Passive Income and Financial Freedom Justin Donald',
        category: 'Books',
        price: '₹196.00 ₹350.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/41IMFnHvpkL._AC_SX184_.jpg',
    },
    {
        id: 29,
        title: 'THE GREATEST KASHMIRI STORIES EVER TOLDTHE GREATEST KASHMIRI STORIES EVER TOLD Neerja Mattoo',
        category: 'Books',
        price: '₹545.00 ₹699.00',
        img: 'https://images-eu.ssl-images-amazon.com/images/I/31WVG1LWhYL._AC_SX184_.jpg',
    },
]
export default menu;